version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "5244:80"
#    depends_on:
#      - db
#    environment:
#      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=db;Username=user;Password=password

volumes:
  postgres_data:
